name = "test-layers"
version = "1.0.0"

[layers]
[[layer]]
name = "os-ubuntu"
type = "git"
url = "https://github.com/brandonrc/os-layer-template.git"
branch_or_tag = "main"

[[layer]]
type = "local"
name = "test-layer-1"

[[layer]]
type = "local"
name = "test-layer-2"

[[layer]]
type = "local"
name = "test-layer-3"
